# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .ipvs import *
from .provider import *
from .random import *
from ._inputs import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_linux.ipvs as __ipvs
    ipvs = __ipvs
else:
    ipvs = _utilities.lazy_import('pulumi_linux.ipvs')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "linux",
  "mod": "index",
  "fqn": "pulumi_linux",
  "classes": {
   "linux:index:Ipvs": "Ipvs",
   "linux:index:Random": "Random"
  }
 },
 {
  "pkg": "linux",
  "mod": "ipvs",
  "fqn": "pulumi_linux.ipvs",
  "classes": {
   "linux:ipvs:Service": "Service"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "linux",
  "token": "pulumi:providers:linux",
  "fqn": "pulumi_linux",
  "class": "Provider"
 }
]
"""
)
